

lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

title: Sammy's Blog
email: sammy@digitalocean.com
description: >
 Welcome to my blog!
github_username: DigitalOcean
twitter_username: DigitalOcean
